=== littlemole/moe/cg/xml/resource.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="qualified" 
           elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:mol="urn:mol-codegen" targetNamespace="urn:mol-codegen">

  <!-- cmd identifiers -->  
  <xs:complexType name="cmds">
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="cmd" minOccurs="0">
          <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required" />
            <xs:attribute name="title" type="xs:string" use="optional" />
            <xs:attribute name="ribbon" type="xs:string" use="optional" />
            <xs:attribute name="notify" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
  </xs:complexType>
  
  <!-- opaque resource ids to define -->
  <xs:complexType name="resource">
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="value" type="xs:int" use="required" />
      <xs:attribute name="type" type="xs:string" use="optional" />
      <xs:attribute name="src" type="xs:string" use="optional" />
  </xs:complexType>
  
  <!-- dialogs -->
  <xs:complexType name="dialogs">
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="dialog" type="mol:dialog" />
      </xs:sequence>
  </xs:complexType>
  
  <!-- control ids -->
  <xs:complexType name="controls">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element maxOccurs="unbounded" name="window">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
      <xs:element maxOccurs="unbounded" name="control">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>

  <!-- type libraries -->
  <xs:complexType name="typelibs">
    <xs:sequence>
      <xs:element name="typelib">
        <xs:complexType>
          <xs:attribute name="src" type="xs:string" use="required" />
          <xs:attribute name="key" type="xs:unsignedByte" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- icons -->
  <xs:complexType name="icons">
    <xs:sequence>
      <xs:element name="icon">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required" />
          <xs:attribute name="src" type="xs:string" use="required" />
          <xs:attribute name="value" type="xs:string" use="optional" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- bitmaps -->
  <xs:complexType name="bitmaps">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="bitmap">
        <xs:complexType>
          <xs:sequence minOccurs="0">
            <xs:element maxOccurs="unbounded" name="index">
              <xs:complexType>
                <xs:attribute name="cmd" type="xs:string" use="required" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="id" type="xs:string" use="required" />
          <xs:attribute name="src" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- accellerators -->
  <xs:complexType name="accelerators">
    <xs:sequence>
      <xs:element name="acceltable">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" name="accelerator">
              <xs:complexType>
                <xs:attribute name="cmd" type="xs:string" use="required" />
                <xs:attribute name="ch" type="xs:string" use="optional" />
                <xs:attribute name="flags" type="xs:string" use="required" />
                <xs:attribute name="key" type="xs:string" use="optional" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="id" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- olemenuitems -->
  <xs:complexType name="olemenuitem">
    <xs:attribute name="cmd" type="xs:string" use="required" />
  </xs:complexType>

  <!-- olemenu -->
  <xs:complexType name="olemenu">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="mol:olemenuitem" name="file"/>
      <xs:element type="mol:olemenuitem" name="window" />
      <xs:element type="mol:olemenuitem" name="help" />
    </xs:choice>
    <xs:attribute name="menu" type="xs:string" use="required" />
  </xs:complexType>

  <!-- olecmd -->
  <xs:complexType name="olecmd">
    <xs:attribute name="cmd" type="xs:string" use="required" />
    <xs:attribute name="oletarget" type="xs:string" use="required" />
  </xs:complexType>
  
  <!-- olecmds -->
  <xs:complexType name="olecmds">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="mol:olecmd" name="olecmd"/>
    </xs:choice>
  </xs:complexType>
  
  <!-- setter -->
  <xs:complexType name="set">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="member" type="xs:string" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <!-- adder -->
  <xs:complexType name="add">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="member" type="xs:string" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- statusbar -->
  <xs:complexType name="statusbar">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="set" type="mol:set" />
      <xs:element name="window" type="mol:childwindow" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
    <xs:attribute name="pos" type="xs:string" use="required" />
  </xs:complexType>

  <!-- childwindow -->
  <xs:complexType name="childwindow">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" name="set" type="mol:set" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="add" type="mol:add" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
    <xs:attribute name="pos" type="xs:string" use="required" />
    <xs:attribute name="visible" type="xs:boolean" use="optional" />
    <xs:attribute name="layout" type="xs:string" use="optional" />
    <xs:attribute name="advise" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- toolbutton -->
  <xs:complexType name="toolbutton">
    <xs:attribute name="cmd" type="xs:string" use="required" />
    <xs:attribute name="dropdown" type="xs:boolean" use="optional" />
  </xs:complexType>

  <!-- active or inactive elements -->
  <xs:complexType name="activeORinactive">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="toolbutton" type="mol:toolbutton" />
    </xs:sequence>
  </xs:complexType>

  <!-- toolbar -->
  <xs:complexType name="toolbar">
    <xs:sequence>
      <xs:element minOccurs="0" type="mol:activeORinactive" name="active" />
      <xs:element minOccurs="0" type="mol:activeORinactive" name="inactive" />
    </xs:sequence>
    <xs:attribute name="class" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="icons" type="xs:unsignedByte" use="required" />
    <xs:attribute name="bmp" type="xs:string" use="required" />
    <xs:attribute name="width" type="xs:unsignedByte" use="required" />
    <xs:attribute name="height" type="xs:unsignedByte" use="required" />
    <xs:attribute name="visible" type="xs:boolean" use="optional" />
  </xs:complexType>

  <!-- bar -->
  <xs:complexType mixed="true" name="bar">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" name="add" type="mol:add" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="set" type="mol:set" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
    <xs:attribute name="width" type="xs:unsignedByte" use="required" />
    <xs:attribute name="height" type="xs:unsignedByte" use="required" />
    <xs:attribute name="visible" type="xs:boolean" use="required" />
  </xs:complexType>

  <!-- rebar -->
  <xs:complexType name="rebar">
    <xs:choice maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" name="toolbar" type="mol:toolbar"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" type="mol:bar" name="bar" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
    <xs:attribute name="pos" type="xs:string" use="required" />
    <xs:attribute name="visible" type="xs:boolean" use="required" />
    <xs:attribute name="layout" type="xs:string" use="required" />
  </xs:complexType>

  <!-- msg -->
  <xs:complexType name="msg">
    <xs:attribute name="handler" type="xs:string" use="optional" />
    <xs:attribute name="stdhandler" type="xs:string" use="optional" />
    <xs:attribute name="cmd" type="xs:string" use="optional" />
    <xs:attribute name="command" type="xs:string" use="optional" />
    <xs:attribute name="msg" type="xs:string" use="optional" />
    <xs:attribute name="layout" type="xs:string" use="optional" />
    <xs:attribute name="ole" type="xs:string" use="optional" />
    <xs:attribute name="interface" type="xs:string" use="optional" />
    <xs:attribute name="params" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- msgrange -->
  <xs:complexType name="msgrange">
    <xs:attribute name="handler" type="xs:string" use="optional" />
    <xs:attribute name="stdhandler" type="xs:string" use="optional" />
    <xs:attribute name="from" type="xs:string" use="optional" />
    <xs:attribute name="to" type="xs:string" use="optional" />
    <xs:attribute name="type" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- notify -->
  <xs:complexType name="notify">
    <xs:attribute name="handler" type="xs:string" use="optional" />
    <xs:attribute name="stdhandler" type="xs:string" use="optional" />
    <xs:attribute name="ctrl" type="xs:string" use="optional" />
    <xs:attribute name="code" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- class -->
  <xs:complexType name="class">
    <xs:choice maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" name="msg" type="mol:msg"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="msgrange" type="mol:msgrange"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="notify" type="mol:notify"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="persist" type="mol:persist"/>
    </xs:choice>
    <xs:attribute name="type" type="xs:string" use="required" />
  </xs:complexType>
  
  <!-- msgs -->
  <xs:complexType name="msgs">
    <xs:choice maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" name="class" type="mol:class"/>
    </xs:choice>
  </xs:complexType>

  <!-- persist -->
  <xs:complexType name="persist">
    <xs:attribute name="property" type="xs:string" use="optional" />
    <xs:attribute name="vtype" type="xs:string" use="optional" />
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="member" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- persistence -->
  <xs:complexType name="persistence">
    <xs:choice maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" name="persist" type="mol:persist"/>
    </xs:choice>
  </xs:complexType>


  <!-- dialog -->
  <xs:complexType name="dialog">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="msgs" type="mol:msgs" />
      <xs:element name="controls" type="mol:controls" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="class" type="xs:string" use="optional" />
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="menu" type="xs:string" use="optional" />
    <xs:attribute name="layout" type="xs:string" use="optional" />
    <xs:attribute name="pos" type="xs:string" use="optional" />
    <xs:attribute name="mdi" type="xs:string" use="optional" />
    <xs:attribute name="persistFile" type="xs:string" use="optional" />
    <xs:attribute name="persistStorage" type="xs:string" use="optional" />
    <xs:attribute name="dragDrop" type="xs:string" use="optional" />
    <xs:attribute name="show" type="xs:string" use="optional" />
    <xs:attribute name="accel" type="xs:string" use="optional" />
  </xs:complexType>

  <!-- window -->
  <xs:complexType name="window">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="olemenu" type="mol:olemenu" />
      <xs:element name="olecmds" type="mol:olecmds" />
      <xs:element name="window" type="mol:childwindow" />
      <xs:element name="statusbar" type="mol:statusbar" />
      <xs:element name="rebar" type="mol:rebar" />
      <xs:element name="msgs" type="mol:msgs" />
      <xs:element name="persistence" type="mol:persistence" />
      <xs:element name="dialog" type="mol:dialog" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
    <xs:attribute name="id" type="xs:string" use="optional" />
    <xs:attribute name="menu" type="xs:string" use="optional" />
    <xs:attribute name="layout" type="xs:string" use="optional" />
    <xs:attribute name="pos" type="xs:string" use="required" />
    <xs:attribute name="mdi" type="xs:string" use="optional" />
    <xs:attribute name="persistFile" type="xs:string" use="optional" />
    <xs:attribute name="persistStorage" type="xs:string" use="optional" />
    <xs:attribute name="dragDrop" type="xs:string" use="optional" />
    <xs:attribute name="show" type="xs:string" use="optional" />
    <xs:attribute name="accel" type="xs:string" use="optional" />
    <xs:attribute name="accessor" type="xs:string" use="optional" />
  </xs:complexType>


  <!-- child window -->
  <xs:complexType name="child">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="window" type="mol:childwindow" />
      <xs:element name="statusbar" type="mol:statusbar" />
      <xs:element name="rebar" type="mol:rebar" />
      <xs:element name="msgs" type="mol:msgs" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
    <xs:attribute name="menu" type="xs:string" use="optional" />
    <xs:attribute name="layout" type="xs:string" use="optional" />
    <xs:attribute name="pos" type="xs:string" use="optional" />
    <xs:attribute name="show" type="xs:string" use="optional" />
  </xs:complexType>
  
  <!-- mdi child window -->
  <xs:complexType name="mdi">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="olemenu" type="mol:olemenu" />
      <xs:element name="olecmds" type="mol:olecmds" />
      <xs:element name="window" type="mol:childwindow" />
      <xs:element name="statusbar" type="mol:statusbar" />
      <xs:element name="rebar" type="mol:rebar" />
      <xs:element name="msgs" type="mol:msgs" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
    <xs:attribute name="menu" type="xs:string" use="optional" />
    <xs:attribute name="layout" type="xs:string" use="optional" />
    <xs:attribute name="pos" type="xs:string" use="optional" />
    <xs:attribute name="mdi" type="xs:string" use="optional" />
    <xs:attribute name="show" type="xs:string" use="optional" />
  </xs:complexType>
  
  <!-- menu -->
  <xs:complexType name="menu" >
    <xs:sequence minOccurs="0">
      <xs:element minOccurs="0" maxOccurs="unbounded" name="menu" type="mol:menu"  />
    </xs:sequence>
    <xs:attribute name="cmd" type="xs:string" use="optional" />
    <xs:attribute name="checked" type="xs:boolean" use="optional" />
    <xs:attribute name="separator" type="xs:boolean" use="optional" />
    <xs:attribute name="enabled" type="xs:boolean" use="optional" />
    <xs:attribute name="popup" type="xs:boolean" use="optional" />
    <xs:attribute name="id" type="xs:string" use="optional" />
    <xs:attribute name="bmp" type="xs:string" use="optional" />
  </xs:complexType>
  
  <!-- menus -->
  <xs:complexType name="menus">
    <xs:sequence maxOccurs="unbounded" minOccurs="0">
      <xs:element maxOccurs="unbounded" name="menu" type="mol:menu" />
    </xs:sequence>
  </xs:complexType>

  <!-- resources :) -->
  <xs:complexType name="resources">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="resource" maxOccurs="unbounded" type="mol:resource" />
      <xs:element name="dialogs" type="mol:dialogs" />
      <xs:element name="controls" type="mol:controls" />
      <xs:element name="typelibs" type="mol:typelibs" />
      <xs:element name="icons" type="mol:icons" />
      <xs:element name="bitmaps" type="mol:bitmaps" />
      <xs:element name="accelerators" type="mol:accelerators"  />
    </xs:choice>
  </xs:complexType>
  
  <!-- ui :) -->
  <xs:complexType name="ui">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="window" type="mol:window" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="mdi" type="mol:mdi" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="child" type="mol:mdi" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
  </xs:complexType>
  
  <!-- codegen, the root element -->
  <xs:element name="codegen">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element maxOccurs="unbounded" name="include" type="xs:string" />
        <xs:element name="cmds" type="mol:cmds" />        
        <xs:element name="menus" type="mol:menus" />
        <xs:element name="ui" type="mol:ui" />
        <xs:element name="msgs" type="mol:msgs" />
        <xs:element name="resources" type="mol:resources" />
      </xs:choice>
      <xs:attribute name="class" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== littlemole/moe/ax/scintillax/xml/resource.xml
<mol:codegen class="ScintillAxGUIBuilder"
               xmlns="urn:mol-codegen"
               xmlns:mol="urn:mol-codegen"
               xmlns:xs="http://www.w3.org/2001/XMLSchema"
			   xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
			   xsi:schemaLocation='urn:mol-codegen resource.xsd'>

  <mol:resources>


    <!-- special resources and stuff we need command identifiers for -->

    <resource  id="IDC_STATIC" value="-1" />


    <!-- dialogs are still created the classic way. here we define only the necessary IDs -->

    <dialogs>
      <!-- scintillax property dialog -->
      <dialog id="IDD_DIALOG_PROP" >
        
        <!-- dialog child control ids  -->
        <controls>
          <control id="IDC_RADIO_UNIX" />
          <control id="IDC_RADIO_WIN32" />
          <control id="IDC_COMBO_ENCODING" />
          <control id="IDC_EDIT_TABWIDTH" />
          <control id="IDC_CHECK_USETABS" />
          <control id="IDC_CHECK_BACKSPACEUNINDENTS" />
          <control id="IDC_CHECK_TABINDENTS" />
          <control id="IDC_CONVERT_BUTTON" />
          <control id="IDC_CHECK_WRITEBOM" />
          <control id="IDC_CHECK_LINE_NUMBERS" />

        </controls>
      </dialog>

      <dialog id="IDD_DIALOG_ENC" >
        <control id="IDC_LIST_ENCODING" />
      </dialog>

    </dialogs>
    <!-- other controls we just define ids for -->

    <controls >

    </controls>

    <!-- typelib to be included in app resources -->
    <typelibs >
      <typelib src="scintillax.tlb" key="1" />
    </typelibs>

    <!-- icon resources to be embedded in app resource-->
    <icons >
      <icon id="IDI_SCINTILLA" src=".\\scintillax.ico"/>
    </icons>

    <!-- bitmap resources, for toolbar bmps optionally a 
        mapping of toolbar button to cmd identifier -->


    <!-- accelerators -->


  </mol:resources>
</mol:codegen>

=== littlemole/moe/bin/moe/xml/include.xml
<mol:codegen class="MoeWndGUIBuilder" 
               xmlns="urn:mol-codegen" 
               xmlns:mol="urn:mol-codegen" 
               xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			   xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
			   xsi:schemaLocation='urn:mol-codegen resource.xsd'>
  
  <!--
  define the necessary includes to be added to generated cpp files 
  -->

  <include>app.h</include>
  <include>dir3.h</include>
  <include>scpdir.h</include>
  <include>editor.h</include>
  <include>taileditor.h</include>
  <include>hex.h</include>
  <include>html.h</include>
  <include>img.h</include>
  <include>ole.h</include>
  <include>form.h</include>
  <include>rtf.h</include>
  <include>Docs.h</include>
  <include>MoeBar.h</include>
  <include>mtree.h</include>
  <include>win/msghandler.h</include>
</mol:codegen>

=== littlemole/moe/cg/xml/resource.xml
<mol:resources class="ScintillAxGUIBuilder" 
               xmlns="urn:Scintilla.ScintillAx" 
               xmlns:mol="urn:Scintilla.ScintillAx" 
               xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			   xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
			   xsi:schemaLocation='urn:Scintilla.ScintillAx resource.xsd'>
 
  <include>app.h</include>
  
  <!-- special resources and stuff we need command identifiers for -->

  <resource  id="IDC_STATIC" value="-1" />


  <!-- dialogs are still created the classic way. here we define only the necessary IDs -->
  <dialogs >
  </dialogs>

  <!-- other controls we just define ids for -->

  <controls >        

  </controls>
  
  <!-- typelib to be included in app resources -->
  <typelibs >
    <typelib src=".\\Debug\\scintillax.tlb" key="1" />
  </typelibs>
  
  <!-- icon resources to be embedded in app resource-->
  <icons >
    <icon id="IDI_SCINTILLA" src=".\\scintillax.ico"/>
  </icons>

  <!-- 
      bitmap resources, for toolbar bmps optionally a 
      mapping of toolbar button to cmd identifier 
  -->

  
  <!-- accelerators -->

  
</mol:resources>

=== littlemole/moe/ax/scintillax/xml/persist.xml
<mol:codegen class="ScintillAxGUIBuilder" 
               xmlns="urn:mol-codegen" 
               xmlns:mol="urn:mol-codegen" 
               xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			         xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
			         xsi:schemaLocation='urn:mol-codegen resource.xsd'>

  
   
   <persistence>
      <class type="ScintillAx">
		    <persist property="DISPID_SCI_FILENAME" vtype="VT_BSTR" name="filename" />	
		    <persist property="DISPID_SCI_READONLY" vtype="VT_BOOL" name="readonly" />	
		    <persist property="DISPID_SCI_SYNTAX" vtype="VT_I4" name="syntax" />	 
		    <persist property="DISPID_SCI_ENCODING" vtype="VT_I4" name="encoding" />	 
		    <persist property="DISPID_SCI_TABUSAGE" vtype="VT_BOOL" name="tabusage" />
		    <persist property="DISPID_SCI_TABINDENTS" vtype="VT_BOOL" name="tabindents" />
		    <persist property="DISPID_SCI_BACKSPACEUNINDENTS" vtype="VT_BOOL" name="backspaceunindents" />	
		    <persist property="DISPID_SCI_TABWIDTH" vtype="VT_I4" name="tabwidth" />	    
		    <persist property="DISPID_SCI_OVERTYPE" vtype="VT_BOOL" name="overtype" />	    
		    <persist property="DISPID_SCI_USECONTEXT" vtype="VT_BOOL"  name="usecontext"/>	    
		    <persist property="DISPID_FONT" vtype="VT_FONT" name="font" />	    
	      <persist member="sizel" name="cs" />
      </class>
    </persistence>


</mol:codegen>

=== littlemole/moe/cg/xml/ui.xml
<mol:resources class="ScintillAxGUIBuilder" 
               xmlns="urn:Scintilla.ScintillAx" 
               xmlns:mol="urn:Scintilla.ScintillAx" 
               xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			         xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
			         xsi:schemaLocation='urn:Scintilla.ScintillAx resource.xsd'>
  
  <include >../scieditor.h</include>
  <include >../ScintillACtrl.h</include>
  <include >../ScintillAxProp.h</include>
  <include >ole/persist.h</include>
  <include>win/layout.h</include>
  
   
  <!-- main GUI description -->
  <ui >

    <!-- the scintilla ax ctrl -->
    <window name="ScintillaActiveXControl" class="ScintillAx"
            layout="BorderLayout" pos="stdRect" id="IDW_SCINTILLA_AX" >
      
      <!-- windows messages scintillax is listening to-->
      <msgs>
        <msg  handler="OnCreate" msg="WM_CREATE" />
	      <notify handler="OnUpdateUI" code="SCN_UPDATEUI" />
	      <notify handler="OnChar" code="SCN_CHARADDED" />
	      <notify handler="OnDblClick" code="SCN_DOUBLECLICK" />
      </msgs>

      <!-- persistence for scintillax-->
	    <persistence>
		    <persist property="DISPID_SCI_FILENAME" vtype="VT_BSTR" name="filename" />	
		    <persist property="DISPID_SCI_READONLY" vtype="VT_BOOL" name="readonly" />	
		    <persist property="DISPID_SCI_SYNTAX" vtype="VT_I4" name="syntax" />	 
		    <persist property="DISPID_SCI_ENCODING" vtype="VT_I4" name="encoding" />	 
		    <persist property="DISPID_SCI_TABUSAGE" vtype="VT_BOOL" name="tabusage" />
		    <persist property="DISPID_SCI_TABINDENTS" vtype="VT_BOOL" name="tabindents" />
		    <persist property="DISPID_SCI_BACKSPACEUNINDENTS" vtype="VT_BOOL" name="backspaceunindents" />	
		    <persist property="DISPID_SCI_TABWIDTH" vtype="VT_I4" name="tabwidth" />	    
		    <persist property="DISPID_SCI_OVERTYPE" vtype="VT_BOOL" name="overtype" />	    
		    <persist property="DISPID_SCI_USECONTEXT" vtype="VT_BOOL"  name="usecontext"/>	    
		    <persist property="DISPID_FONT" vtype="VT_FONT" name="font" />	    
	      <persist member="sizel" name="cs" />	    
	    </persistence>

      <!-- child window holding native scintilla widget -->
      <window name="editor" id="IDC_EDITOR_VIEW" class="EditWnd" pos="mol::stdRect"
              visible="true" layout="BorderLayout::FILL" >
		    <set member="UsePopUp">true</set>          
		    <set member="CodePage">CP_UTF8</set>          
		    <set member="ScrollWidth">120</set>          
		    <set member="MarginWidth">1,0</set>          
		    <set member="TabWidth">4</set>
	    </window>
    


    </window>
  
  </ui>

  <dialogs>
    <!-- scintillax property dialog -->
    <dialog name="scintillaproperties" id="IDD_DIALOG_PROP" class="ScintillAxProperties">

      <!-- window messages from dialog -->
      <msgs>
        <msg  handler="OnInitDialog" msg="WM_INITDIALOG" />
        <msg  handler="OnDirty" cmd="IDC_RADIO_UNIX"  />
        <msg  handler="OnDirty" cmd="IDC_RADIO_WIN32"  />
        <msg  handler="OnDirty" cmd="IDC_COMBO_ENCODING"  />
        <msg  handler="OnDirty" cmd="IDC_CHECK_USETABS"  />
        <msg  handler="OnDirty" cmd="IDC_CHECK_TABINDENTS"  />
        <msg  handler="OnDirty" cmd="IDC_EDIT_TABWIDTH"  />
        <msg  handler="OnDirty" cmd="IDC_CHECK_BACKSPACEUNINDENTS"  />
        <msg  handler="OnDirty" cmd="IDC_CHECK_WRITEBOM"  />
        <msg  handler="OnConvert" cmd="IDC_CONVERT_BUTTON"  />
      </msgs>

      <!-- dialog child control ids  -->
      <controls>
        <control id="IDC_RADIO_UNIX" />
        <control id="IDC_RADIO_WIN32" />
        <control id="IDC_COMBO_ENCODING" />
        <control id="IDC_EDIT_TABWIDTH" />
        <control id="IDC_CHECK_USETABS" />
        <control id="IDC_CHECK_BACKSPACEUNINDENTS" />
        <control id="IDC_CHECK_TABINDENTS" />
        <control id="IDC_CONVERT_BUTTON" />
        <control id="IDC_CHECK_WRITEBOM" />
      </controls>
    </dialog>
  </dialogs>

</mol:resources>

=== littlemole/moe/ax/scintillax/xml/include.xml
<mol:codegen class="ScintillAxGUIBuilder" 
               xmlns="urn:mol-codegen" 
               xmlns:mol="urn:mol-codegen" 
               xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			         xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
			         xsi:schemaLocation='urn:mol-codegen resource.xsd'>
  
  <include >scieditor.h</include>
  <include >ScintillACtrl.h</include>
  <include >ScintillAxProp.h</include>
  <include >Properties.h</include>
  <include >ole/persist.h</include>
  <include>win/layout.h</include>
  <include>win/msghandler.h</include>
  <include>ScintillAx_dispid.h</include>


</mol:codegen>
